# Generated by Django 3.2.9 on 2021-12-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок публикации')),
                ('publish_datetime', models.CharField(max_length=100, verbose_name='Дата и время публикации')),
                ('full_text', models.TextField(verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to=None, verbose_name='Фото')),
                ('timeline', models.BooleanField(default=True, verbose_name='Виден в таймлайне?')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
