# Generated by Django 3.2.9 on 2021-12-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
