# Generated by Django 3.2.9 on 2021-12-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview_text',
            field=models.TextField(default='', verbose_name='Текст статьи'),
            preserve_default=False,
        ),
    ]
