# Generated by Django 3.2.9 on 2021-12-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20211204_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='full_text',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
    ]
