# Generated by Django 3.2.9 on 2021-12-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.AddField(
            model_name='news',
            name='photo_url',
            field=models.URLField(default='', max_length=900, verbose_name='Ссылка на фото'),
            preserve_default=False,
        ),
    ]
