# Generated by Django 3.2.9 on 2021-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20211204_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
        migrations.AddField(
            model_name='news',
            name='source_url',
            field=models.URLField(default='', max_length=900, verbose_name='Ссылка на источник'),
            preserve_default=False,
        ),
    ]
